### ISSUE TITLE
New version build

### ISSUE THREAD

**Issue by RaSKoR** [DutchForeigner/signal-cli_rpi#1]
Hello @DutchForeigner ,

First, thank you very much for your signal-cli build's. I'm using it on my Rpi4 running Debian10 without issue.

Will you build newer version of signal-cli ?

Regards,
R_K

**Comment by DutchForeigner** [comment]
I would like to be able to also build the newer version (signal-cli v 0.7.4), but the build is failing on my raspberry 3B (Gradle crashes).
looking at some other comments, It _might_ have to do with available free memory. I dont have a Rpi4 with more memory (yet).

**Comment by DutchForeigner** [comment]
I've managed to build signal-cli v0.7.4 on my Raspberry Pi 3B now. Source code is in the repo now.
