### ISSUE TITLE
Missing libraries signal-client and libzkgroup

### ISSUE THREAD

**Issue by androbey** [DutchForeigner/signal-cli_rpi#2]
Hi, 

first of all thanks for work and your detailed manual (which is really great!). 

I followed all the steps just like you outlined in your manual on a Raspberry Pi with latest Raspberry OS. 
Building the libraries worked (or seemed to work) without any problems. 

But when I tried to send a test message I got the error that signal-client is missing (when trying to start dbus system it also said missing libzkgroup). 
I then copied both lib files to java library path and now I can send messages again but still get error about new groups (WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup). 

I was wondering if this step is still required if one follows your manual? I supposed it is not, but I also don't get why it's not working. I checked both libsignal-client version and libzkgroup version.

**Comment by DutchForeigner** [comment]
Hi androbey,
On the newer versions of signal-cli (>0.7.1) there is another library which needs to build and included.
I've compiled  signal-cli v0.8.1 tar file, for on the Raspberry Pi, and it is on my Github page, together with an updated 'manual'
[Gitub link](https://github.com/DutchForeigner/signal-cli_rpi)

When I can find some time, I'll try to compile the current version v0.8.4, but it's not always easy due to the limited memory on a Rasberry Pi 3.

**Comment by androbey** [comment]
Hi @DutchForeigner, 
thank you for your reply. 
Actually, I used your updated manual already. Building libsignal (signal-client) and libzkgroup worked (at least as it seemed) without  any problems. 

On the other hand, I am using a Raspberry Pi 4 (2GB). I guess using the tar file you build for the RPI 3 won't work?

**Comment by DutchForeigner** [comment]
@androbey 
As far as I know, there is no difference between the raspberry pi 3 and 4, OS wise, so the tar file should also work on a raspberry pi 4 as long as the OS is raspbian buster. I'll try to compile v0.8.4 and see if I can get it to work and update here with the results.

**Comment by androbey** [comment]
@DutchForeigner You are right, thank you! I just tried your provided tar file and it seems to work just fine (no error or warning messages so far). Thank you very much. 

However, it's still strange it doesn't work when I build it myself.

**Comment by DutchForeigner** [comment]
@androbey, I've just found that there was a missing copy step in the v0.8.1 manual, I've updated that now.
I've now also compiled signal-cli version v.0.8.4, but have not yet tested it. Once I get it registered and a test message send, I'll upload the updated manual and tar file.

**Comment by androbey** [comment]
@DutchForeigner Actually, I did this copy step already (as you wrote "Copy 2 files" already), so that was probably not the cause for my problem.

**Comment by DutchForeigner** [comment]
@androbey  I managed to get signal-cli v0.8.3 compiled (only tested with sending a test message), but v0.8.4 I'm not able to get working. It might be related to issue [#643](https://github.com/AsamK/signal-cli/issues/643). If that is indeed the case, we wont be able to use signal-cli v0.8.4 on the Raspberry Pi, as you cannot really update the glibc package/library as it is part of the OS and Debian 10/buster comes with v2.28
