### ISSUE TITLE
are you coming with a new version?

### ISSUE THREAD

**Issue by Tsjippy** [DutchForeigner/signal-cli_rpi#5]
version 0.9.0?

**Comment by DutchForeigner** [comment]
Hi, had not planned it, as I ve.moved to an Intel box.
That said, with you asking for it, I'll try to get the latest version compiled for you early this week.

**Comment by DutchForeigner** [comment]
I've released V0.9.0 compiled for the Raspberry Pi.

**Comment by Tsjippy** [comment]
thanks so much
